// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsHd9DRcg5jpp1dNsEQFmFe2mcR6bTLA',
    appId: '1:835858854447:web:8d53a27fa430b4ea688cda',
    messagingSenderId: '835858854447',
    projectId: 'proyecto-carro-basurero',
    authDomain: 'proyecto-carro-basurero.firebaseapp.com',
    storageBucket: 'proyecto-carro-basurero.appspot.com',
    measurementId: 'G-5M250HE80K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMsqubKGxzO3vmiBd0_3uC_F7HyD1V3E',
    appId: '1:835858854447:android:ce5a0b3ccbca3de5688cda',
    messagingSenderId: '835858854447',
    projectId: 'proyecto-carro-basurero',
    storageBucket: 'proyecto-carro-basurero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcS5EhtQPQcjb1b6Ch7GsaXoKG8cv3BEw',
    appId: '1:835858854447:ios:ee8efc68b0c21159688cda',
    messagingSenderId: '835858854447',
    projectId: 'proyecto-carro-basurero',
    storageBucket: 'proyecto-carro-basurero.appspot.com',
    androidClientId: '835858854447-t6fi6t2mvtidj404llq85cmhi2dofsig.apps.googleusercontent.com',
    iosClientId: '835858854447-dbikmnn54keo9ij5a9620gnqiacas3sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCarroBasurero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcS5EhtQPQcjb1b6Ch7GsaXoKG8cv3BEw',
    appId: '1:835858854447:ios:ee8efc68b0c21159688cda',
    messagingSenderId: '835858854447',
    projectId: 'proyecto-carro-basurero',
    storageBucket: 'proyecto-carro-basurero.appspot.com',
    androidClientId: '835858854447-t6fi6t2mvtidj404llq85cmhi2dofsig.apps.googleusercontent.com',
    iosClientId: '835858854447-dbikmnn54keo9ij5a9620gnqiacas3sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCarroBasurero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgsHd9DRcg5jpp1dNsEQFmFe2mcR6bTLA',
    appId: '1:835858854447:web:c6dfac4ed83e2ad3688cda',
    messagingSenderId: '835858854447',
    projectId: 'proyecto-carro-basurero',
    authDomain: 'proyecto-carro-basurero.firebaseapp.com',
    storageBucket: 'proyecto-carro-basurero.appspot.com',
    measurementId: 'G-NWENT09CCD',
  );
}
